accessibility_issues_in_full_page:
  applies_to: SiteAdmin
  state: hidden
  display_name: Accessibility issues in full page
  description: |-
    Accessibility issues will be available in full page instead of drawer.
  environments:
    ci:
      state: allowed
    development:
      state: allowed
