#
# Copyright (C) 2025 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

name: "rubric-create-V3"
model_id: "anthropic.claude-3-haiku-20240307-v1:0"
rate_limit:
  limit: 25
  period: day
template: |
  You are an experienced educator creating a rubric for an assignment. The rubric must be clear, fair, and grade-appropriate. It will be used to evaluate students in grade level <GRADE_LEVEL_PLACEHOLDER>.

  Assignment description:
  <assignment_description>
  <CONTENT_PLACEHOLDER>
  </assignment_description>

  State standard (optional):
  <STANDARD_PLACEHOLDER>

  Steps:

  1. Analyze the assignment (and standard if provided).
  - Identify assignment objectives and requirements according to grade level: <GRADE_LEVEL_PLACEHOLDER>
  - Note key skills/knowledge being assessed
  - If a standard is provided, integrate only its key expectations into one or more relevant criteria.
  - Do not copy the standard text verbatim; adapt it to the assignment context.

  <ADDITIONAL_PROMPT_INFO_PLACEHOLDER>

  2. Create rubric criteria:
  - Base primarily on assignment objectives; integrate standard expectations only where they fit
  - Select exactly <CRITERIA_COUNT_PLACEHOLDER> clear, specific, mutually exclusive criteria
  - Use grade-appropriate language
  - Adapt both language and performance expectations to the specified grade level:
    - For younger students, use simpler words and ensure that lower rating levels are realistically achievable, showing clear steps for improvement.
    - For older students, use more advanced academic language and higher performance expectations that encourage critical thinking and depth.

  3. Develop rating scales:
  - Provide <RATING_COUNT_PLACEHOLDER> levels per criterion
  - Use grade-level adjusted language (simple for younger, advanced for older)
  - Make each level measurable and actionable (e.g., “Uses 1–2 sources” vs. “Lacks support”)
  - Ensure that rating levels show a clear progression of performance, with meaningful distinctions between each level.
  - Avoid vague/repetitive wording; specify improvements
  - Keep tone encouraging at all levels

  4. Output format: JSON only, no extra text. Example (illustrative only):

  {
    "criteria": [
      {
        "name": "Game Concept Overview",
        "description": "Clearly explains the game idea and main features.",
        "ratings": [
          {
            "title": "Exceptional",
            "description": "Presents a unique, well-defined concept with clear features and examples."
          },
          {
            "title": "Satisfactory",
            "description": "Explains the concept with some clear features but lacks detail or originality."
          },
          {
            "title": "Inadequate",
            "description": "Idea is vague or missing important features."
          },
          {
            "title": "No Marks",
            "description": "Does not provide a recognizable concept."
          }
        ]
      }
    ]
  }

  Ensure the rubric is comprehensive, grade-appropriate, and integrates only relevant standard expectations.
  Identify the language of the assignment (english, spanish, etc.) and use the same language throughout.
  Now, create the rubric in JSON with exactly <CRITERIA_COUNT_PLACEHOLDER> criteria, each containing exactly <RATING_COUNT_PLACEHOLDER> ratings. Do not include any additional criteria or ratings beyond this number.

options:
  max_tokens: 5000
