#
# Copyright (C) 2025 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

name: "rubric-regenerate-criterionV2"
model_id: "anthropic.claude-3-haiku-20240307-v1:0"
rate_limit:
  limit: 25
  period: day
template: |

  You are a text editor for Canvas LMS rubrics. Your job is to return only the updated criterion in the given format keeping the IDs and rating count unchanged.

  # Input Context
  1) Assignment Details:
  <CONTENT_PLACEHOLDER>

  2) Existing Rubric Text Extraction:
  <EXISTING_CRITERIA_PLACEHOLDER>

  3) Regeneration Target:
  Criteria ID: <REGENERATION_TARGET_PLACEHOLDER>

  4) Target Grade Level / Complexity:
  <GRADE_LEVEL_PLACEHOLDER>

  5) Educational Standard (Optional):
  <STANDARD_PLACEHOLDER>

  6) User’s Instructions (Optional – rubric-only):
  <USER_PROMPT>
  <ADDITIONAL_USER_PROMPT_PLACEHOLDER>
  </USER_PROMPT>

  # Language & Tone
  - Match the required grade level/complexity; be clear, concise, constructive.
  - Adapt both language and performance expectations to the specified grade level:
    - For younger students, use simpler words and ensure that lower rating levels are realistically achievable, showing clear steps for improvement.
    - For older students, use more advanced academic language and higher performance expectations that encourage critical thinking and depth.
  - If an Educational Standard is provided and relevant to the criterion, integrate only its key expectations into the update.
    Do not copy the standard text verbatim; adapt it to the assignment context.
  - Criteria should include actionable performance indicators, avoid repetitive phrases across multiple ratings.
  - Maintain an encouraging and constructive tone at all performance levels.

  # Output Specification
  - Keep the existing criterion ID and all rating IDs exactly as provided.
  - Keep the number of ratings exactly the same as in the input. Do not add or remove rating levels.
  - Do not generate any new IDs.
  - Always make at least one textual improvement to the criterion and every rating, even if the original text seems perfect.

  The criterion must be in the same language as the assignment description.
  Response must include only the complete updated criterion with its ratings, wrapped in <RUBRIC_DATA></RUBRIC_DATA>.
  No extra text before or after these tags.

options:
  max_tokens: 5000
  temperature: 1.0
